services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=products-cluster
      - CASSANDRA_DC=datacenter1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE keyspaces'"]
      interval: 15s
      timeout: 15s
      retries: 10
    networks:
      - cassandra-net

  cassandra-init:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra-init:/cassandra-init
    command:
      /bin/bash -c "until cqlsh cassandra -f /cassandra-init/init.cql; do echo 'Waiting for Cassandra'; sleep 10; done"
    networks:
      - cassandra-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra:9042
      - SPRING_CASSANDRA_KEYSPACE_NAME=products
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_CASSANDRA_SCHEMA_ACTION=create_if_not_exists
      - SPRING_CASSANDRA_REQUEST_TIMEOUT=30s
      - SPRING_CASSANDRA_CONNECTION_CONNECT_TIMEOUT=30s
      - SPRING_CASSANDRA_CONNECTION_INIT_QUERY_TIMEOUT=30s
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
    networks:
      - cassandra-net

volumes:
  cassandra-data:

networks:
  cassandra-net:
    driver: bridge